server:
  port: ${PORT:50101}

spring:
  application:
    name: xc‐govern‐center

  # 安全认证
  security:
    user:
      name: user
      password: 123


eureka:
  client:
    #服务注册，是否将自己注册到Eureka服务中
    registerWithEureka: true
    #服务发现，是否从Eureka中获取注册信息
    fetchRegistry: true
    #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果 不配置则默认本机8761端口）
    serviceUrl:
      defaultZone: ${SERVER_URL:http://user:123@eureka02:50102/eureka/}
  server:
    #是否开启自我保护模式
    enable‐self‐preservation: false
    #服务注册表清理间隔（单位毫秒，默认是60*1000）
    eviction‐interval‐timer‐in‐ms: 60000

  instance:
    hostname: ${DOMAIN_NAME:eureka01}



