server:
  port: ${PORT:31001}
  servlet:
    context-path: /cms

spring:
  application:
    name: xc-service-manage-cms

  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: xc_cms

  # rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /

eureka:
  client:
    #服务注册开关
    registerWithEureka: true
    #服务发现开关
    fetchRegistry: true
    serviceUrl:
      #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://user:123@192.168.99.100:50101/eureka/,http://user:123@192.168.99.100:50102/eureka/}
    instance:
      #将自己的ip地址注册到Eureka服务中
      prefer‐ip‐address: true
      ip‐address: ${IP_ADDRESS:127.0.0.1}
      #指定实例id`
      instance‐id: ${spring.application.name}:${server.port}

ribbon:
  #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试 MaxAutoRetriesNextServer:    3    #切换实例的重试次数
  MaxAutoRetries: 2
  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作 没有实现幂等的情况下是很危险的,所以设置为false
  OkToRetryOnAllOperations: false
  #请求连接的超时时间
  ConnectTimeout: 5000
  #请求处理的超时时间
  ReadTimeout: 6000
